// Mock data for demo mode — rich, realistic Vietnamese job market data
import { Company, Job, Resume, Skill } from '@/types/job.types';
import { User } from '@/types/auth.types';
import { NotificationItem } from '@/types/notification.types';
import { PremiumPackage } from '@/types/premium.types';

// ============================================================
// SKILLS
// ============================================================
export const MOCK_SKILLS: Skill[] = [
  { id: 1, name: 'React' },
  { id: 2, name: 'Java' },
  { id: 3, name: 'Spring Boot' },
  { id: 4, name: 'TypeScript' },
  { id: 5, name: 'Python' },
  { id: 6, name: 'Node.js' },
  { id: 7, name: 'SQL' },
  { id: 8, name: 'Docker' },
  { id: 9, name: 'AWS' },
  { id: 10, name: 'React Native' },
  { id: 11, name: 'Flutter' },
  { id: 12, name: 'Figma' },
  { id: 13, name: 'UI/UX Design' },
  { id: 14, name: 'Marketing' },
  { id: 15, name: 'SEO' },
  { id: 16, name: 'Data Analysis' },
  { id: 17, name: 'Machine Learning' },
  { id: 18, name: 'DevOps' },
  { id: 19, name: 'Kubernetes' },
  { id: 20, name: 'MongoDB' },
];

// ============================================================
// COMPANIES
// ============================================================
export const MOCK_COMPANIES: Company[] = [
  {
    id: 1,
    name: 'FPT Software',
    description: 'Công ty công nghệ hàng đầu Việt Nam với hơn 30.000 nhân viên. Chuyên gia về Digital Transformation, Cloud, AI/ML và Software Outsourcing.',
    address: 'Tòa nhà FPT, Phố Duy Tân, Cầu Giấy, Hà Nội',
    logo: '',
    website: 'https://fpt-software.com',
    size: '10,000+',
    industry: 'Công nghệ thông tin',
    isPremium: true,
    premiumTier: 'ENTERPRISE',
    jobCount: 45,
  },
  {
    id: 2,
    name: 'VNG Corporation',
    description: 'Unicorn công nghệ Việt Nam, phát triển các sản phẩm Zalo, ZaloPay, và nhiều game nổi tiếng.',
    address: 'Z06 đường số 13, KCX Tân Thuận, Quận 7, TP.HCM',
    logo: '',
    website: 'https://vng.com.vn',
    size: '5,000+',
    industry: 'Công nghệ thông tin',
    isPremium: true,
    premiumTier: 'PRO',
    jobCount: 32,
  },
  {
    id: 3,
    name: 'Viettel Digital',
    description: 'Trung tâm công nghệ số thuộc Tập đoàn Viettel. Phát triển các giải pháp số cho doanh nghiệp và chính phủ.',
    address: 'Tòa nhà Viettel, 01 Giang Văn Minh, Ba Đình, Hà Nội',
    logo: '',
    size: '3,000+',
    industry: 'Viễn thông & CNTT',
    isPremium: true,
    premiumTier: 'ENTERPRISE',
    jobCount: 28,
  },
  {
    id: 4,
    name: 'Shopee Việt Nam',
    description: 'Sàn thương mại điện tử hàng đầu khu vực Đông Nam Á.',
    address: 'Tầng 4-5-6, Tòa Etown Central, Quận 4, TP.HCM',
    logo: '',
    size: '2,000+',
    industry: 'Thương mại điện tử',
    isPremium: true,
    premiumTier: 'PRO',
    jobCount: 22,
  },
  {
    id: 5,
    name: 'Techcombank',
    description: 'Ngân hàng TMCP Kỹ Thương Việt Nam - một trong những ngân hàng tư nhân lớn nhất Việt Nam.',
    address: '191 Bà Triệu, Hai Bà Trưng, Hà Nội',
    logo: '',
    size: '10,000+',
    industry: 'Ngân hàng & Tài chính',
    isPremium: false,
    jobCount: 15,
  },
  {
    id: 6,
    name: 'MoMo',
    description: 'Ví điện tử và siêu ứng dụng tài chính hàng đầu Việt Nam với hơn 40 triệu người dùng.',
    address: 'Tầng 18, Tòa Saigon Centre, Quận 1, TP.HCM',
    logo: '',
    size: '1,500+',
    industry: 'Fintech',
    isPremium: true,
    premiumTier: 'BASIC',
    jobCount: 18,
  },
  {
    id: 7,
    name: 'Tiki',
    description: 'Nền tảng thương mại điện tử Việt Nam với mô hình TikiNOW giao hàng 2h.',
    address: '52 Út Tịch, Tân Bình, TP.HCM',
    logo: '',
    size: '3,000+',
    industry: 'Thương mại điện tử',
    isPremium: false,
    jobCount: 12,
  },
  {
    id: 8,
    name: 'VNPAY',
    description: 'Công ty công nghệ tài chính cung cấp giải pháp thanh toán điện tử tại Việt Nam.',
    address: '22 Láng Hạ, Đống Đa, Hà Nội',
    logo: '',
    size: '1,000+',
    industry: 'Fintech',
    isPremium: false,
    jobCount: 8,
  },
  {
    id: 9,
    name: 'Grab Vietnam',
    description: 'Siêu ứng dụng hàng đầu Đông Nam Á - Gọi xe, giao hàng, thanh toán.',
    address: 'Tầng 12, Lim Tower, Quận 1, TP.HCM',
    logo: '',
    size: '1,000+',
    industry: 'Công nghệ & Giao thông',
    isPremium: true,
    premiumTier: 'PRO',
    jobCount: 20,
  },
  {
    id: 10,
    name: 'Creative Agency VN',
    description: 'Agency sáng tạo hàng đầu chuyên về branding, digital marketing và thiết kế.',
    address: '45 Nguyễn Huệ, Quận 1, TP.HCM',
    logo: '',
    size: '50-200',
    industry: 'Marketing & Quảng cáo',
    isPremium: false,
    jobCount: 5,
  },
];

// ============================================================
// JOBS
// ============================================================
const now = new Date().toISOString();
const weekAgo = new Date(Date.now() - 7 * 86400000).toISOString();
const monthLater = new Date(Date.now() + 30 * 86400000).toISOString();

export const MOCK_JOBS: Job[] = [
  {
    id: 1,
    name: 'Senior React Developer',
    description: 'Tìm kiếm Senior React Developer có kinh nghiệm xây dựng ứng dụng web quy mô lớn. Bạn sẽ tham gia phát triển các sản phẩm Digital Transformation cho khách hàng quốc tế.\n\n• Thiết kế và phát triển giao diện người dùng với React/Next.js\n• Code review và mentor junior developers\n• Tối ưu hiệu suất ứng dụng\n• Làm việc với team Agile/Scrum',
    location: 'Hà Nội',
    salary: 45000000,
    quantity: 3,
    level: 'SENIOR',
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[3], MOCK_SKILLS[5]],
    company: MOCK_COMPANIES[0],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isPremium: true,
    isUrgent: true,
    isSaved: false,
    isApplied: false,
    matchScore: 92,
    viewCount: 1250,
    applicantCount: 23,
  },
  {
    id: 2,
    name: 'Java Spring Boot Developer',
    description: 'Gia nhập đội ngũ Backend để xây dựng hệ thống microservices phục vụ hàng triệu người dùng Zalo.\n\n• Phát triển RESTful APIs với Spring Boot\n• Thiết kế database và tối ưu query\n• Triển khai CI/CD pipeline\n• Đảm bảo code quality và security',
    location: 'Hồ Chí Minh',
    salary: 40000000,
    quantity: 5,
    level: 'MIDDLE',
    skills: [MOCK_SKILLS[1], MOCK_SKILLS[2], MOCK_SKILLS[6], MOCK_SKILLS[7]],
    company: MOCK_COMPANIES[1],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isPremium: true,
    isSaved: true,
    isApplied: false,
    matchScore: 85,
    viewCount: 980,
    applicantCount: 18,
  },
  {
    id: 3,
    name: 'React Native Mobile Developer',
    description: 'Phát triển ứng dụng mobile cross-platform cho hệ sinh thái Viettel.\n\n• Xây dựng app React Native cho iOS và Android\n• Tích hợp với backend APIs\n• Tối ưu hiệu suất và UX\n• Viết unit test và integration test',
    location: 'Hà Nội',
    salary: 35000000,
    quantity: 2,
    level: 'MIDDLE',
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[9], MOCK_SKILLS[3]],
    company: MOCK_COMPANIES[2],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isPremium: true,
    isUrgent: true,
    isSaved: false,
    isApplied: false,
    matchScore: 95,
    viewCount: 756,
    applicantCount: 12,
  },
  {
    id: 4,
    name: 'Full Stack Developer (Node.js + React)',
    description: 'Tham gia đội ngũ sản phẩm tại Shopee để xây dựng các tính năng e-commerce.\n\n• Phát triển full stack với Node.js backend và React frontend\n• Xử lý hệ thống high-traffic\n• Làm việc với microservices architecture\n• A/B testing và data-driven development',
    location: 'Hồ Chí Minh',
    salary: 50000000,
    quantity: 4,
    level: 'SENIOR',
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[5], MOCK_SKILLS[3], MOCK_SKILLS[8]],
    company: MOCK_COMPANIES[3],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isPremium: true,
    isSaved: false,
    isApplied: false,
    matchScore: 78,
    viewCount: 2100,
    applicantCount: 45,
  },
  {
    id: 5,
    name: 'Data Analyst',
    description: 'Phân tích dữ liệu kinh doanh và khách hàng tại Techcombank.\n\n• Thu thập và phân tích dữ liệu từ nhiều nguồn\n• Tạo reports và dashboards\n• Đưa ra insights hỗ trợ quyết định kinh doanh\n• Làm việc với SQL, Python, Power BI',
    location: 'Hà Nội',
    salary: 25000000,
    quantity: 2,
    level: 'JUNIOR',
    skills: [MOCK_SKILLS[4], MOCK_SKILLS[6], MOCK_SKILLS[15]],
    company: MOCK_COMPANIES[4],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isSaved: false,
    isApplied: false,
    matchScore: 62,
    viewCount: 543,
    applicantCount: 30,
  },
  {
    id: 6,
    name: 'DevOps Engineer',
    description: 'Xây dựng và vận hành hạ tầng cloud cho MoMo.\n\n• Quản lý infrastructure trên AWS/GCP\n• Triển khai và quản lý Kubernetes clusters\n• Xây dựng CI/CD pipelines\n• Monitoring và alerting systems',
    location: 'Hồ Chí Minh',
    salary: 55000000,
    quantity: 1,
    level: 'SENIOR',
    skills: [MOCK_SKILLS[7], MOCK_SKILLS[8], MOCK_SKILLS[17], MOCK_SKILLS[18]],
    company: MOCK_COMPANIES[5],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isPremium: true,
    isUrgent: true,
    isSaved: false,
    isApplied: false,
    matchScore: 45,
    viewCount: 890,
    applicantCount: 8,
  },
  {
    id: 7,
    name: 'UI/UX Designer',
    description: 'Thiết kế trải nghiệm người dùng cho các sản phẩm e-commerce tại Tiki.\n\n• Nghiên cứu người dùng và tạo user personas\n• Thiết kế wireframes, mockups và prototypes\n• Làm việc chặt chẽ với team Product và Engineering\n• Xây dựng và duy trì Design System',
    location: 'Hồ Chí Minh',
    salary: 28000000,
    quantity: 2,
    level: 'MIDDLE',
    skills: [MOCK_SKILLS[11], MOCK_SKILLS[12]],
    company: MOCK_COMPANIES[6],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isSaved: true,
    isApplied: false,
    matchScore: 30,
    viewCount: 670,
    applicantCount: 22,
  },
  {
    id: 8,
    name: 'Backend Developer (Python)',
    description: 'Phát triển hệ thống thanh toán tại VNPAY.\n\n• Xây dựng APIs với Python/FastAPI\n• Xử lý giao dịch real-time\n• Tối ưu performance và security\n• Viết unit tests',
    location: 'Hà Nội',
    salary: 32000000,
    quantity: 3,
    level: 'MIDDLE',
    skills: [MOCK_SKILLS[4], MOCK_SKILLS[6], MOCK_SKILLS[7]],
    company: MOCK_COMPANIES[7],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isSaved: false,
    isApplied: true,
    matchScore: 70,
    viewCount: 445,
    applicantCount: 15,
  },
  {
    id: 9,
    name: 'Machine Learning Engineer',
    description: 'Nghiên cứu và phát triển mô hình ML/AI cho Grab Vietnam.\n\n• Xây dựng recommendation systems\n• Phát triển NLP models\n• Triển khai models lên production\n• Phân tích và xử lý big data',
    location: 'Hồ Chí Minh',
    salary: 60000000,
    quantity: 2,
    level: 'SENIOR',
    skills: [MOCK_SKILLS[4], MOCK_SKILLS[16], MOCK_SKILLS[7]],
    company: MOCK_COMPANIES[8],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isPremium: true,
    isSaved: false,
    isApplied: false,
    matchScore: 55,
    viewCount: 1500,
    applicantCount: 10,
  },
  {
    id: 10,
    name: 'Digital Marketing Specialist',
    description: 'Quản lý và tối ưu chiến dịch marketing online.\n\n• Lên kế hoạch và triển khai chiến dịch ads\n• SEO/SEM optimization\n• Phân tích hiệu quả chiến dịch\n• Content marketing và social media',
    location: 'Hồ Chí Minh',
    salary: 18000000,
    quantity: 2,
    level: 'JUNIOR',
    skills: [MOCK_SKILLS[13], MOCK_SKILLS[14], MOCK_SKILLS[15]],
    company: MOCK_COMPANIES[9],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isSaved: false,
    isApplied: false,
    matchScore: 25,
    viewCount: 320,
    applicantCount: 40,
  },
  {
    id: 11,
    name: 'Flutter Mobile Developer',
    description: 'Xây dựng ứng dụng mobile đa nền tảng cho hệ thống ngân hàng số.\n\n• Phát triển app Flutter cho iOS và Android\n• Tích hợp biometric authentication\n• Xử lý bảo mật dữ liệu tài chính\n• Tối ưu UX cho giao dịch ngân hàng',
    location: 'Hà Nội',
    salary: 30000000,
    quantity: 2,
    level: 'MIDDLE',
    skills: [MOCK_SKILLS[10], MOCK_SKILLS[3]],
    company: MOCK_COMPANIES[4],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isSaved: false,
    isApplied: false,
    matchScore: 40,
    viewCount: 380,
    applicantCount: 14,
  },
  {
    id: 12,
    name: 'Fresher Java Developer',
    description: 'Cơ hội cho các bạn mới ra trường yêu thích Java.\n\n• Được training bài bản về Spring Boot\n• Tham gia dự án thực tế từ tuần đầu\n• Mentor 1-1 từ Senior Developer\n• Lộ trình thăng tiến rõ ràng',
    location: 'Hà Nội',
    salary: 12000000,
    quantity: 10,
    level: 'FRESHER',
    skills: [MOCK_SKILLS[1], MOCK_SKILLS[2], MOCK_SKILLS[6]],
    company: MOCK_COMPANIES[0],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isPremium: true,
    isSaved: false,
    isApplied: false,
    matchScore: 88,
    viewCount: 2500,
    applicantCount: 120,
  },
  {
    id: 13,
    name: 'Product Manager',
    description: 'Quản lý sản phẩm thanh toán số tại MoMo.\n\n• Xác định vision và roadmap sản phẩm\n• Phân tích data và user research\n• Phối hợp với các team Engineering, Design, Marketing\n• Quản lý backlog và sprint planning',
    location: 'Hồ Chí Minh',
    salary: 50000000,
    quantity: 1,
    level: 'SENIOR',
    skills: [MOCK_SKILLS[15]],
    company: MOCK_COMPANIES[5],
    active: true,
    startDate: weekAgo,
    endDate: monthLater,
    createdAt: weekAgo,
    isPremium: true,
    isSaved: false,
    isApplied: false,
    matchScore: 35,
    viewCount: 1100,
    applicantCount: 30,
  },
  {
    id: 14,
    name: 'Intern Frontend Developer',
    description: 'Chương trình thực tập 6 tháng tại VNG.\n\n• Học React/Vue.js từ cơ bản đến nâng cao\n• Tham gia dự án thực tế\n• Hỗ trợ 5 triệu/tháng\n• Cơ hội trở thành nhân viên chính thức',
    location: 'Hồ Chí Minh',
    salary: 5000000,
    quantity: 15,
    level: 'INTERN',
    skills: [MOCK_SKILLS[0], MOCK_SKILLS[3]],
    company: MOCK_COMPANIES[1],
    active: true,
    startDate: now,
    endDate: monthLater,
    createdAt: now,
    isPremium: true,
    isSaved: false,
    isApplied: false,
    matchScore: 80,
    viewCount: 3200,
    applicantCount: 200,
  },
];

// ============================================================
// MOCK USER (current logged in user)
// ============================================================
export const MOCK_CURRENT_USER: User = {
  id: 1,
  email: 'demo@topjob.vn',
  name: 'Nguyễn Văn An',
  phone: '0987654321',
  age: 25,
  gender: 'MALE',
  address: 'Quận Cầu Giấy, Hà Nội',
  skills: ['React', 'TypeScript', 'Java', 'Spring Boot', 'React Native', 'Node.js', 'SQL'],
  role: { id: 1, name: 'USER', active: true },
  createdAt: '2024-01-15T00:00:00Z',
};

// ============================================================
// APPLICATIONS (Resumes)
// ============================================================
export const MOCK_APPLICATIONS: Resume[] = [
  {
    id: 1,
    email: 'demo@topjob.vn',
    url: '/uploads/cv_nguyen_van_an.pdf',
    status: 'REVIEWING',
    companyName: 'FPT Software',
    jobName: 'Senior React Developer',
    job: { id: 1, name: 'Senior React Developer' },
    user: { id: 1, name: 'Nguyễn Văn An' },
    createdAt: '2024-12-01T09:00:00Z',
    createdBy: 'demo@topjob.vn',
  },
  {
    id: 2,
    email: 'demo@topjob.vn',
    url: '/uploads/cv_nguyen_van_an.pdf',
    status: 'APPROVED',
    companyName: 'VNG Corporation',
    jobName: 'Java Spring Boot Developer',
    job: { id: 2, name: 'Java Spring Boot Developer' },
    user: { id: 1, name: 'Nguyễn Văn An' },
    createdAt: '2024-11-20T14:30:00Z',
    createdBy: 'demo@topjob.vn',
  },
  {
    id: 3,
    email: 'demo@topjob.vn',
    url: '/uploads/cv_nguyen_van_an.pdf',
    status: 'PENDING',
    companyName: 'VNPAY',
    jobName: 'Backend Developer (Python)',
    job: { id: 8, name: 'Backend Developer (Python)' },
    user: { id: 1, name: 'Nguyễn Văn An' },
    createdAt: '2024-12-05T10:00:00Z',
    createdBy: 'demo@topjob.vn',
  },
  {
    id: 4,
    email: 'demo@topjob.vn',
    url: '/uploads/cv_nguyen_van_an.pdf',
    status: 'REJECTED',
    companyName: 'Shopee Việt Nam',
    jobName: 'Full Stack Developer',
    job: { id: 4, name: 'Full Stack Developer (Node.js + React)' },
    user: { id: 1, name: 'Nguyễn Văn An' },
    createdAt: '2024-10-15T08:00:00Z',
    createdBy: 'demo@topjob.vn',
  },
];

// ============================================================
// NOTIFICATIONS
// ============================================================
const today = new Date();
const yesterday = new Date(today.getTime() - 86400000);
const twoDaysAgo = new Date(today.getTime() - 2 * 86400000);

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: '1',
    type: 'JOB_MATCH',
    title: 'Việc làm phù hợp 95%!',
    body: 'React Native Mobile Developer tại Viettel Digital rất phù hợp với kỹ năng của bạn.',
    read: false,
    createdAt: today.toISOString(),
    data: { jobId: 3 },
    icon: '',
  },
  {
    id: '2',
    type: 'APPLICATION_UPDATE',
    title: 'Đơn ứng tuyển được cập nhật',
    body: 'FPT Software đang xem xét hồ sơ của bạn cho vị trí Senior React Developer.',
    read: false,
    createdAt: today.toISOString(),
    data: { applicationId: 1, jobId: 1 },
    icon: '',
  },
  {
    id: '3',
    type: 'APPLICATION_UPDATE',
    title: 'Chúc mừng! Hồ sơ được chấp nhận',
    body: 'VNG Corporation đã chấp nhận hồ sơ của bạn cho vị trí Java Spring Boot Developer. Vui lòng chờ liên hệ phỏng vấn.',
    read: false,
    createdAt: yesterday.toISOString(),
    data: { applicationId: 2, jobId: 2 },
    icon: '',
  },
  {
    id: '4',
    type: 'NEW_JOB',
    title: 'Việc làm mới từ FPT Software',
    body: 'FPT Software vừa đăng 3 vị trí mới phù hợp với bạn.',
    read: true,
    createdAt: yesterday.toISOString(),
    data: { companyId: 1 },
    icon: '',
  },
  {
    id: '5',
    type: 'COMPANY_VIEW',
    title: 'Nhà tuyển dụng xem CV của bạn',
    body: 'MoMo vừa xem CV của bạn. Họ có thể liên hệ sớm!',
    read: true,
    createdAt: twoDaysAgo.toISOString(),
    data: { companyId: 6 },
    icon: '',
  },
  {
    id: '6',
    type: 'JOB_MATCH',
    title: 'Việc làm mới phù hợp với bạn',
    body: 'Chúng tôi tìm thấy 5 việc làm mới có điểm match trên 80%.',
    read: true,
    createdAt: twoDaysAgo.toISOString(),
    icon: '🤖',
  },
  {
    id: '7',
    type: 'SYSTEM',
    title: 'Hoàn thiện hồ sơ để tăng cơ hội',
    body: 'Hồ sơ của bạn đã hoàn thiện 75%. Thêm kinh nghiệm làm việc để tăng match score.',
    read: true,
    createdAt: twoDaysAgo.toISOString(),
    icon: '🔔',
  },
];

// ============================================================
// PREMIUM PACKAGES
// ============================================================
export const MOCK_PREMIUM_PACKAGES: PremiumPackage[] = [
  {
    id: 'basic',
    name: 'Basic',
    tier: 'BASIC',
    price: 500000,
    currency: 'VND',
    duration: 1,
    color: '#6366F1',
    icon: '',
    features: [
      { name: 'Đăng tối đa 5 tin tuyển dụng/tháng', included: true },
      { name: 'Hiển thị logo công ty', included: true },
      { name: 'Xem 50 hồ sơ ứng viên/tháng', included: true },
      { name: 'Badge "Đã xác minh"', included: true },
      { name: 'Đẩy tin lên top', included: false },
      { name: 'AI gợi ý ứng viên phù hợp', included: false },
      { name: 'Báo cáo analytics chi tiết', included: false },
      { name: 'Hỗ trợ chuyên viên riêng', included: false },
    ],
  },
  {
    id: 'pro',
    name: 'Pro',
    tier: 'PRO',
    price: 1500000,
    currency: 'VND',
    duration: 1,
    isPopular: true,
    color: '#F59E0B',
    icon: '',
    features: [
      { name: 'Đăng tối đa 20 tin tuyển dụng/tháng', included: true },
      { name: 'Hiển thị logo công ty', included: true },
      { name: 'Xem không giới hạn hồ sơ ứng viên', included: true },
      { name: 'Badge "Premium" nổi bật', included: true },
      { name: 'Đẩy 5 tin lên top/tháng', included: true },
      { name: 'AI gợi ý ứng viên phù hợp', included: true },
      { name: 'Báo cáo analytics chi tiết', included: false },
      { name: 'Hỗ trợ chuyên viên riêng', included: false },
    ],
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    tier: 'ENTERPRISE',
    price: 5000000,
    currency: 'VND',
    duration: 1,
    color: '#10B981',
    icon: '',
    features: [
      { name: 'Đăng không giới hạn tin tuyển dụng', included: true },
      { name: 'Hiển thị logo công ty', included: true },
      { name: 'Xem không giới hạn hồ sơ ứng viên', included: true },
      { name: 'Badge "Enterprise" đặc biệt', included: true },
      { name: 'Đẩy không giới hạn tin lên top', included: true },
      { name: 'AI gợi ý ứng viên phù hợp', included: true },
      { name: 'Báo cáo analytics chi tiết', included: true },
      { name: 'Hỗ trợ chuyên viên riêng 24/7', included: true },
    ],
  },
];

// ============================================================
// SAVED JOB IDS
// ============================================================
export const MOCK_SAVED_JOB_IDS: number[] = [2, 7];
